[2025-07-31T01:40:19.542+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T01:40:19.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_qqqq2222.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T01:40:19.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_qqqq2222.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T01:40:19.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T01:40:19.726+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-31T01:40:19.733+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5770) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T01:40:19.734+0000] {standard_task_runner.py:63} INFO - Started process 5772 to run task
[2025-07-31T01:40:19.734+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_qqqq2222', 'transform_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmpvu8ia_k_']
[2025-07-31T01:40:19.735+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask transform_data_task
[2025-07-31T01:40:19.783+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_qqqq2222.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-31T01:40:19.901+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_qqqq2222' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-31T01:40:19.903+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T01:40:19.918+0000] {__init__.py:92} INFO - 執行 transform_data (資料轉換層)
[2025-07-31T01:40:19.918+0000] {__init__.py:34} INFO - _get_upstream_output_path 上游任務: {'extract_data_task'}
[2025-07-31T01:40:19.918+0000] {__init__.py:50} INFO - 任務 'transform_data_task' 從單一上游 'extract_data_task' 拉取資料
[2025-07-31T01:40:19.926+0000] {__init__.py:52} INFO - 拉取到的 redis_key: ***_data:dag_qqqq2222.extract_data_task
[2025-07-31T01:40:19.929+0000] {__init__.py:115} INFO - 呼叫演算法 'add_test' 來自模組 'processor.transform.algos_2'
[2025-07-31T01:40:19.930+0000] {__init__.py:139} ERROR - transform_data 發生例外: add_test() missing 1 required positional argument: 'output_filename'
[2025-07-31T01:40:19.930+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T01:40:19.931+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 117, in transform_data
    processed_data = func(data_list, **algo_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: add_test() missing 1 required positional argument: 'output_filename'
[2025-07-31T01:40:19.944+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_qqqq2222, task_id=transform_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250731T014019, end_date=20250731T014019
[2025-07-31T01:40:19.964+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 113 for task transform_data_task (add_test() missing 1 required positional argument: 'output_filename'; 5772)
[2025-07-31T01:40:19.987+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T01:40:20.003+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T01:40:20.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
