[2025-07-30T13:33:12.775+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T13:33:12.885+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_csssssssssbbb.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T13:33:12.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_csssssssssbbb.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T13:33:12.890+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-30T13:33:12.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-30T13:33:12.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5560) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T13:33:12.906+0000] {standard_task_runner.py:63} INFO - Started process 5562 to run task
[2025-07-30T13:33:12.906+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_csssssssssbbb', 'transform_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmpffkmj2sb']
[2025-07-30T13:33:12.908+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask transform_data_task
[2025-07-30T13:33:12.957+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_csssssssssbbb.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-30T13:33:13.054+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_csssssssssbbb' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-30T13:33:13.056+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T13:33:13.071+0000] {__init__.py:104} INFO - 執行 transform_data (資料轉換層)
[2025-07-30T13:33:13.072+0000] {__init__.py:42} INFO - _get_upstream_output_path 上游任務: {'extract_data_task', 'extract_data_task2222'}
[2025-07-30T13:33:13.089+0000] {__init__.py:151} ERROR - transform_data 發生例外: name 'results' is not defined
[2025-07-30T13:33:13.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T13:33:13.089+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 107, in transform_data
    upstream_redis_keys = _get_upstream_output_path(ti)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 57, in _get_upstream_output_path
    logger.info(f"多上游任務拉到的 XCom 清單: {results}")
                                               ^^^^^^^
NameError: name 'results' is not defined
[2025-07-30T13:33:13.105+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_csssssssssbbb, task_id=transform_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250730T133312, end_date=20250730T133313
[2025-07-30T13:33:13.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task transform_data_task (name 'results' is not defined; 5562)
[2025-07-30T13:33:13.159+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T13:33:13.176+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T13:33:13.178+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
