[2025-07-31T00:53:48.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T00:53:48.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_qweqweqweqwe.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T00:53:48.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_qweqweqweqwe.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T00:53:48.355+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T00:53:48.370+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-31T00:53:48.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3025) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T00:53:48.378+0000] {standard_task_runner.py:63} INFO - Started process 3027 to run task
[2025-07-31T00:53:48.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_qweqweqweqwe', 'extract_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmp9lulg1em']
[2025-07-31T00:53:48.381+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask extract_data_task
[2025-07-31T00:53:48.443+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_qweqweqweqwe.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-31T00:53:48.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_qweqweqweqwe' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-31T00:53:48.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T00:53:48.603+0000] {__init__.py:56} INFO - 執行 extract_data (資料載入層)
[2025-07-31T00:53:48.603+0000] {__init__.py:75} ERROR - extract_data 發生例外: name 'pd' is not defined
[2025-07-31T00:53:48.603+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T00:53:48.604+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 58, in extract_data
    algo_module = importlib.import_module(algorithm_module)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/processor/extract/readNP.py", line 4, in <module>
    def test_csv(input_filename: str,**kwargs) -> pd.DataFrame:
                                                  ^^
NameError: name 'pd' is not defined
[2025-07-31T00:53:48.612+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_qweqweqweqwe, task_id=extract_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250731T005348, end_date=20250731T005348
[2025-07-31T00:53:48.623+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 106 for task extract_data_task (name 'pd' is not defined; 3027)
[2025-07-31T00:53:48.632+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T00:53:48.653+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T00:53:48.658+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
