[2025-07-30T05:58:14.251+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T05:58:14.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_iiiiiiiii.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T05:58:14.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_iiiiiiiii.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T05:58:14.296+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-30T05:58:14.305+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-30T05:58:14.313+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1087) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T05:58:14.314+0000] {standard_task_runner.py:63} INFO - Started process 1089 to run task
[2025-07-30T05:58:14.313+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_iiiiiiiii', 'transform_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmpoosky783']
[2025-07-30T05:58:14.315+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask transform_data_task
[2025-07-30T05:58:14.559+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_iiiiiiiii.transform_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-30T05:58:14.654+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_iiiiiiiii' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-30T05:58:14.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T05:58:14.668+0000] {logging_mixin.py:188} INFO - 測試轉換層
[2025-07-30T05:58:14.668+0000] {logging_mixin.py:188} INFO - transform_data_task
[2025-07-30T05:58:14.668+0000] {logging_mixin.py:188} INFO - 任務 'transform_data_task' 正在從上游 'extract_data_task' 拉取資料...
[2025-07-30T05:58:14.668+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T05:58:14.668+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 73, in transform_data
    test = _get_upstream_output_path(ti)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 41, in _get_upstream_output_path
    pulled_path_str = ti.xcom_pull(key=OUTPUT_PATH_XCOM_KEY, task_ids=upstream_task_id)
                                       ^^^^^^^^^^^^^^^^^^^^
NameError: name 'OUTPUT_PATH_XCOM_KEY' is not defined
[2025-07-30T05:58:14.677+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_iiiiiiiii, task_id=transform_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250730T055814, end_date=20250730T055814
[2025-07-30T05:58:14.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task transform_data_task (name 'OUTPUT_PATH_XCOM_KEY' is not defined; 1089)
[2025-07-30T05:58:14.728+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T05:58:14.890+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T05:58:14.893+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
