[2025-07-28T07:46:01.209+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T07:46:01.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_999999999999.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-28T07:46:01.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_999999999999.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-28T07:46:01.236+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-28T07:46:01.244+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-28T07:46:01.251+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_999999999999', 'extract_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmpmf0ptn06']
[2025-07-28T07:46:01.253+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask extract_data_task
[2025-07-28T07:46:01.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10001) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T07:46:01.364+0000] {standard_task_runner.py:63} INFO - Started process 10003 to run task
[2025-07-28T07:46:01.390+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_999999999999.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 1171f9d2ced8
[2025-07-28T07:46:01.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_999999999999' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-28T07:46:01.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T07:46:01.500+0000] {logging_mixin.py:188} INFO - 2222222222222222222222222222222222222
[2025-07-28T07:46:01.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T07:46:01.501+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 20, in extract_data
    processed_df = func(**algo_kwargs)
                   ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/extract/readCSV.py", line 4, in test_csv
    print(filename)
          ^^^^^^^^
NameError: name 'filename' is not defined
[2025-07-28T07:46:01.510+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_999999999999, task_id=extract_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250728T074601, end_date=20250728T074601
[2025-07-28T07:46:01.521+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task extract_data_task (name 'filename' is not defined; 10003)
[2025-07-28T07:46:01.537+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T07:46:01.562+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T07:46:01.567+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
