[2025-07-30T12:21:58.140+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T12:21:58.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:21:58.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:21:58.273+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-30T12:21:58.286+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-30T12:21:58.292+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1251) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T12:21:58.293+0000] {standard_task_runner.py:63} INFO - Started process 1253 to run task
[2025-07-30T12:21:58.293+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_bllllllllllllllllll', 'extract_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmpox1pn89f']
[2025-07-30T12:21:58.294+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask extract_data_task
[2025-07-30T12:21:58.329+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-30T12:21:58.415+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_bllllllllllllllllll' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-30T12:21:58.416+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T12:21:58.433+0000] {logging_mixin.py:188} INFO - 測試載入層
[2025-07-30T12:21:58.433+0000] {logging_mixin.py:188} INFO - Applying algorithm 'test_csv' from module 'processor.extract.readCSV'
[2025-07-30T12:21:58.434+0000] {logging_mixin.py:188} INFO - 3f2a4b93-b237-4545-bd50-5004d863567c.csv
[2025-07-30T12:21:58.482+0000] {logging_mixin.py:188} INFO - test11111111111111:***_data:extract_data_task
[2025-07-30T12:21:58.486+0000] {logging_mixin.py:188} INFO - Data stored in Redis key: ***_data:extract_data_task
[2025-07-30T12:21:58.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T12:21:58.513+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 71, in extract_data
    pulled_path_str = ti.xcom_pull(key=ti.task_id, task_ids=ti.task_id, all=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'all'
[2025-07-30T12:21:58.532+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_bllllllllllllllllll, task_id=extract_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250730T122158, end_date=20250730T122158
[2025-07-30T12:21:58.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task extract_data_task (TaskInstance.xcom_pull() got an unexpected keyword argument 'all'; 1253)
[2025-07-30T12:21:58.587+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T12:21:58.609+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T12:21:58.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-30T12:27:04.198+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T12:27:04.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:27:04.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:27:04.361+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-30T12:27:04.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-30T12:27:04.382+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1555) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T12:27:04.383+0000] {standard_task_runner.py:63} INFO - Started process 1557 to run task
[2025-07-30T12:27:04.383+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_bllllllllllllllllll', 'extract_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmprk1leq6t']
[2025-07-30T12:27:04.385+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask extract_data_task
[2025-07-30T12:27:04.421+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_bllllllllllllllllll.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-30T12:27:04.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_bllllllllllllllllll' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-30T12:27:04.537+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T12:27:04.556+0000] {logging_mixin.py:188} INFO - 測試載入層
[2025-07-30T12:27:04.557+0000] {logging_mixin.py:188} INFO - Applying algorithm 'test_csv' from module 'processor.extract.readCSV'
[2025-07-30T12:27:04.557+0000] {logging_mixin.py:188} INFO - 3f2a4b93-b237-4545-bd50-5004d863567c.csv
[2025-07-30T12:27:04.572+0000] {logging_mixin.py:188} INFO - test11111111111111:***_data_extract_data_task
[2025-07-30T12:27:04.574+0000] {logging_mixin.py:188} INFO - Data stored in Redis key: ***_data_extract_data_task
[2025-07-30T12:27:04.585+0000] {logging_mixin.py:188} INFO - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
[2025-07-30T12:27:04.585+0000] {logging_mixin.py:188} INFO - set()
[2025-07-30T12:27:04.586+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T12:27:04.586+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 74, in extract_data
    pulled_path_str = ti.xcom_pull(key=ti.task_id, task_ids=ti.task_id, all=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'all'
[2025-07-30T12:27:04.593+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_bllllllllllllllllll, task_id=extract_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250730T122704, end_date=20250730T122704
[2025-07-30T12:27:04.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task extract_data_task (TaskInstance.xcom_pull() got an unexpected keyword argument 'all'; 1557)
[2025-07-30T12:27:04.636+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T12:27:04.675+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T12:27:04.681+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
