[2025-08-04T01:00:05.744+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dag_cccbbbbb.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
