[2025-07-30T12:58:03.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T12:58:03.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ggggggggggggggggg.load_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:58:03.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ggggggggggggggggg.load_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-30T12:58:03.282+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-30T12:58:03.293+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-30T12:58:03.299+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3383) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T12:58:03.300+0000] {standard_task_runner.py:63} INFO - Started process 3392 to run task
[2025-07-30T12:58:03.300+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ggggggggggggggggg', 'load_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmptvc67sk5']
[2025-07-30T12:58:03.302+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask load_data_task
[2025-07-30T12:58:03.333+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ggggggggggggggggg.load_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-30T12:58:03.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ggggggggggggggggg' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-30T12:58:03.386+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T12:58:03.394+0000] {__init__.py:160} INFO - 執行 load_data (資料匯入層)
[2025-07-30T12:58:03.395+0000] {__init__.py:42} INFO - _get_upstream_output_path 上游任務: {'transform_data_task'}
[2025-07-30T12:58:03.395+0000] {__init__.py:62} INFO - 任務 'load_data_task' 從單一上游 'transform_data_task' 拉取資料
[2025-07-30T12:58:03.402+0000] {__init__.py:65} INFO - 拉取到的 redis_key: ***_data:dag_ggggggggggggggggg.transform_data_task
[2025-07-30T12:58:03.402+0000] {__init__.py:175} INFO - 從 Redis 讀取資料，key=***_data:dag_ggggggggggggggggg.transform_data_task
[2025-07-30T12:58:03.423+0000] {__init__.py:186} INFO - 呼叫演算法 'test_csv' 來自模組 'processor.load.saveCSV'
[2025-07-30T12:58:03.427+0000] {__init__.py:192} ERROR - load_data 發生例外: cannot construct a FileSource from    product_id product_name  total_quantity  average_price
0         101       Laptop              15          635.0
1         102        Mouse             150           24.5
2         103     Keyboard              30           75.0
3         104      Monitor              20          300.0
[2025-07-30T12:58:03.428+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T12:58:03.428+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 189, in load_data
    func(data_df, **algo_kwargs)
  File "/opt/airflow/dags/processor/load/saveCSV.py", line 5, in test_csv
    df = pd.read_parquet(data)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 272, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1762, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1326, in __init__
    fragment = parquet_format.make_fragment(single_file, filesystem)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset_parquet.pyx", line 273, in pyarrow._dataset_parquet.ParquetFileFormat.make_fragment
  File "pyarrow/_dataset.pyx", line 1337, in pyarrow._dataset.FileFormat.make_fragment
  File "pyarrow/_dataset.pyx", line 132, in pyarrow._dataset._make_file_source
TypeError: cannot construct a FileSource from    product_id product_name  total_quantity  average_price
0         101       Laptop              15          635.0
1         102        Mouse             150           24.5
2         103     Keyboard              30           75.0
3         104      Monitor              20          300.0
[2025-07-30T12:58:03.435+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ggggggggggggggggg, task_id=load_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250730T125803, end_date=20250730T125803
[2025-07-30T12:58:03.443+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task load_data_task (cannot construct a FileSource from    product_id product_name  total_quantity  average_price
0         101       Laptop              15          635.0
1         102        Mouse             150           24.5
2         103     Keyboard              30           75.0
3         104      Monitor              20          300.0; 3392)
[2025-07-30T12:58:03.473+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T12:58:03.486+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T12:58:03.488+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
